//
//  LocalizationCatalog.swift
//  Ikonlate
//

import Foundation

/// Declares every keyed string and its English development value so Xcode can
/// extract the entries into Localizable.xcstrings at build time.
enum LocalizationCatalog {

    static let resources: [LocalizedStringResource] = [
        LocalizedStringResource("tab.translate", defaultValue: "Translate"),
        LocalizedStringResource("tab.camera", defaultValue: "Camera"),
        LocalizedStringResource("tab.live", defaultValue: "Live"),
        LocalizedStringResource("tab.settings", defaultValue: "Settings"),
        LocalizedStringResource("onboarding.translate.title", defaultValue: "Translate without detours"),
        LocalizedStringResource("onboarding.translate.message", defaultValue: "Choose source and target languages, enter text, and get a selectable translation right away."),
        LocalizedStringResource("onboarding.camera.title", defaultValue: "Capture text by camera"),
        LocalizedStringResource("onboarding.camera.message", defaultValue: "Photograph printed text, recognize it, and open it in the translator."),
        LocalizedStringResource("onboarding.accessibility.title", defaultValue: "Adjusted to you"),
        LocalizedStringResource("onboarding.accessibility.message", defaultValue: "Tune language, contrast, controls, and motion in Settings."),
        LocalizedStringResource("onboarding.button.next", defaultValue: "Next"),
        LocalizedStringResource("onboarding.button.start", defaultValue: "Get started"),
        LocalizedStringResource("translator.importSearch", defaultValue: "Use search text"),
        LocalizedStringResource("translator.importSearchHint", defaultValue: "Copies the search text into the translation field."),
        LocalizedStringResource("translator.from", defaultValue: "From"),
        LocalizedStringResource("translator.to", defaultValue: "To"),
        LocalizedStringResource("translator.supportedLanguages", defaultValue: "%d supported languages loaded"),
        LocalizedStringResource("translator.inputTitle", defaultValue: "Text"),
        LocalizedStringResource("translator.inputPlaceholder", defaultValue: "Enter text"),
        LocalizedStringResource("translator.inputAccessibilityLabel", defaultValue: "Text to translate"),
        LocalizedStringResource("translator.inputAccessibilityHint", defaultValue: "Enter the text that should be translated."),
        LocalizedStringResource("translator.buttonHintSameLanguage", defaultValue: "Choose two different languages."),
        LocalizedStringResource("translator.offlineDownload.button", defaultValue: "Download languages offline"),
        LocalizedStringResource("translator.offlineDownload.loading", defaultValue: "Preparing download"),
        LocalizedStringResource("translator.offlineDownload.confirm.title", defaultValue: "Download languages offline?"),
        LocalizedStringResource("translator.offlineDownload.confirm.message", defaultValue: "%@ and %@ will be prepared for offline translation. iOS may ask again before downloading."),
        LocalizedStringResource("translator.offlineDownload.confirm.action", defaultValue: "Prepare"),
        LocalizedStringResource("translator.offlineDownload.success.title", defaultValue: "Ready offline"),
        LocalizedStringResource("translator.offlineDownload.error.title", defaultValue: "Download unavailable"),
        LocalizedStringResource("translator.offlineDownload.alreadyInstalled", defaultValue: "This language pair is already downloaded and available offline."),
        LocalizedStringResource("translator.offlineDownload.success", defaultValue: "This language pair is prepared for offline use."),
        LocalizedStringResource("translator.offlineDownload.unsupported", defaultValue: "This language pair isn't supported for offline translation on this device."),
        LocalizedStringResource("translator.offlineDownload.error", defaultValue: "Offline download could not be started."),
        LocalizedStringResource("translator.outputTitle", defaultValue: "Result"),
        LocalizedStringResource("translator.loading", defaultValue: "Preparing translation"),
        LocalizedStringResource("translator.preparingLanguages", defaultValue: "Loading or preparing languages"),
        LocalizedStringResource("translator.longPreparation", defaultValue: "Preparing language model. This can take longer the first time."),
        LocalizedStringResource("translator.emptyResult", defaultValue: "Your translation appears here."),
        LocalizedStringResource("translator.resultAccessibilityLabel", defaultValue: "Translation"),
        LocalizedStringResource("translator.resultAccessibilityHint", defaultValue: "The translated text is selectable."),
        LocalizedStringResource("translator.error", defaultValue: "Translation failed. Check the language pair or network for the model download."),
        LocalizedStringResource("speech.start", defaultValue: "Start dictation"),
        LocalizedStringResource("speech.stop", defaultValue: "Stop dictation"),
        LocalizedStringResource("speech.speak", defaultValue: "Speak translation"),
        LocalizedStringResource("speech.listening", defaultValue: "Listening and translating live"),
        LocalizedStringResource("speech.error.permission", defaultValue: "Speech recognition was not allowed."),
        LocalizedStringResource("speech.error.microphone", defaultValue: "Microphone access was not allowed."),
        LocalizedStringResource("speech.error.unavailable", defaultValue: "Speech recognition is not available for this language right now."),
        LocalizedStringResource("speech.error.start", defaultValue: "The microphone could not be started."),
        LocalizedStringResource("speech.error.inputFormat", defaultValue: "The microphone is not providing a valid audio format. Check the simulator or test on a real device."),
        LocalizedStringResource("speech.error.recognition", defaultValue: "Speech recognition was interrupted."),
        LocalizedStringResource("history.title", defaultValue: "History"),
        LocalizedStringResource("history.empty", defaultValue: "No translations yet"),
        LocalizedStringResource("history.emptyFavorites", defaultValue: "No favorites yet"),
        LocalizedStringResource("history.filter.all", defaultValue: "All"),
        LocalizedStringResource("history.filter.favorites", defaultValue: "Favorites"),
        LocalizedStringResource("history.clear", defaultValue: "Clear history"),
        LocalizedStringResource("history.delete", defaultValue: "Delete entry"),
        LocalizedStringResource("history.search.placeholder", defaultValue: "Search history"),
        LocalizedStringResource("history.search.empty", defaultValue: "No matching translations"),
        LocalizedStringResource("history.clear.confirm.title", defaultValue: "Clear history?"),
        LocalizedStringResource("history.clear.confirm.message", defaultValue: "All translations and favorites will be permanently removed."),
        LocalizedStringResource("history.clear.confirm.action", defaultValue: "Delete all"),
        LocalizedStringResource("history.favorite.add", defaultValue: "Mark as favorite"),
        LocalizedStringResource("history.favorite.remove", defaultValue: "Remove favorite"),
        LocalizedStringResource("common.done", defaultValue: "Done"),
        LocalizedStringResource("common.cancel", defaultValue: "Cancel"),
        LocalizedStringResource("live.title", defaultValue: "Live Translation"),
        LocalizedStringResource("live.beta", defaultValue: "BETA"),
        LocalizedStringResource("live.personLanguage", defaultValue: "Person's language"),
        LocalizedStringResource("live.yourLanguage", defaultValue: "Your language"),
        LocalizedStringResource("live.start", defaultValue: "Start translation"),
        LocalizedStringResource("live.stop", defaultValue: "Stop translation"),
        LocalizedStringResource("camera.title", defaultValue: "Camera Translation"),
        LocalizedStringResource("camera.capture", defaultValue: "Take photo"),
        LocalizedStringResource("camera.retake", defaultValue: "Retake"),
        LocalizedStringResource("camera.translate", defaultValue: "Translate recognized text"),
        LocalizedStringResource("camera.useInTranslator", defaultValue: "Open in translator"),
        LocalizedStringResource("camera.placeholder", defaultValue: "Take a photo of text so Vision can recognize it and the Translation API can translate it."),
        LocalizedStringResource("camera.recognizedTitle", defaultValue: "Recognized text"),
        LocalizedStringResource("camera.resultTitle", defaultValue: "Translation"),
        LocalizedStringResource("camera.scanning", defaultValue: "Recognizing text"),
        LocalizedStringResource("camera.translating", defaultValue: "Translating"),
        LocalizedStringResource("camera.noText", defaultValue: "No readable text was found in the photo."),
        LocalizedStringResource("camera.ocrError", defaultValue: "Text recognition failed."),
        LocalizedStringResource("camera.translationError", defaultValue: "Camera translation failed."),
        LocalizedStringResource("settings.section.language", defaultValue: "Language"),
        LocalizedStringResource("settings.appLanguage", defaultValue: "App language"),
        LocalizedStringResource("settings.appLanguageHint", defaultValue: "Switches the app text between German and English."),
        LocalizedStringResource("settings.section.accessibility", defaultValue: "Accessibility"),
        LocalizedStringResource("settings.largeControls", defaultValue: "Larger controls"),
        LocalizedStringResource("settings.largeControlsHint", defaultValue: "Enlarges input fields, buttons, and result text in the translator."),
        LocalizedStringResource("settings.highContrast", defaultValue: "Higher contrast"),
        LocalizedStringResource("settings.highContrastHint", defaultValue: "Improves readability of surfaces and borders."),
        LocalizedStringResource("settings.section.motion", defaultValue: "Motion"),
        LocalizedStringResource("settings.reduceAnimations", defaultValue: "Reduce animations"),
        LocalizedStringResource("settings.reduceAnimationsHint", defaultValue: "Reduces symbol animations and transitions in the app."),
        LocalizedStringResource("settings.section.voiceover", defaultValue: "VoiceOver"),
        LocalizedStringResource("settings.speakResultHint", defaultValue: "Result hint"),
        LocalizedStringResource("settings.speakResultHintHint", defaultValue: "Tells the screen reader that translated text is selectable."),
        LocalizedStringResource("settings.section.history", defaultValue: "History"),
        LocalizedStringResource("settings.historyLimit", defaultValue: "Saved entries"),
        LocalizedStringResource("settings.historyLimitHint", defaultValue: "Sets how many of the newest translations are stored."),
        LocalizedStringResource("settings.historyLimit.value", defaultValue: "%d entries"),
        LocalizedStringResource("settings.historyLimit.unlimited", defaultValue: "Unlimited"),
        LocalizedStringResource("settings.section.appInfo", defaultValue: "App info"),
        LocalizedStringResource("settings.appVersion", defaultValue: "Version"),
        LocalizedStringResource("settings.buildNumber", defaultValue: "Build"),
        LocalizedStringResource("settings.iOSVersion", defaultValue: "iOS version"),
        LocalizedStringResource("settings.bundleIdentifier", defaultValue: "Bundle ID"),
    ]
}
